Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -62,17 +62,19 @@ jobs:
           name: app-debug.apk
           path: bin/*.apk
           
-      - name: Install Android Build Tools
-        run: |
-          yes | $ANDROIDSDK/cmdline-tools/latest/bin/sdkmanager "build-tools;31.0.0"
-
       - name: Install cmdline-tools
         run: |
-          mkdir -p $ANDROIDSDK/cmdline-tools
-          cd $ANDROIDSDK/cmdline-tools
-          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
-          unzip commandlinetools-linux-*.zip -d latest
-
-      - name: Check aidl
-        run: ls -l $ANDROIDSDK/build-tools/31.0.0/aidl || echo "aidl not found"
+          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
+          cd $ANDROID_SDK_ROOT/cmdline-tools
+          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
+          unzip cmdline-tools.zip -d latest
+          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
+      
+      - name: Install Android Build Tools (with aidl)
+        run: |
+          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;30.0.3"
+      
+      - name: Check AIDL exists
+        run: |
+          ls -l $ANDROID_SDK_ROOT/build-tools/30.0.3/aidl || (echo "AIDL not found!" && exit 1)
 
