Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -63,5 +63,16 @@ jobs:
           path: bin/*.apk
           
       - name: Install Android Build Tools
-        run: sdkmanager "build-tools;31.0.0" "platform-tools" "platforms;android-31"
+        run: |
+          yes | $ANDROIDSDK/cmdline-tools/latest/bin/sdkmanager "build-tools;31.0.0"
+
+      - name: Install cmdline-tools
+        run: |
+          mkdir -p $ANDROIDSDK/cmdline-tools
+          cd $ANDROIDSDK/cmdline-tools
+          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
+          unzip commandlinetools-linux-*.zip -d latest
+
+      - name: Check aidl
+        run: ls -l $ANDROIDSDK/build-tools/31.0.0/aidl || echo "aidl not found"
 
